### ISSUE TITLE
Add options to send messages in different formatted style

### ISSUE THREAD

**Issue by imf-ali** [RocketChat/EmbeddedChat#98]
As an EmbedChat developer

**I need to**: Different options available while sending a message. 
This will consist of following options:
1. Bold
2. Italic
3. Strike
4. Code
5. Multiline

**So That**: I can send in specified way as mention above

**Acceptance Criteria**

- [ ] Able to make message bold
- [ ] Able to italic text
- [ ] Able to strike text
- [ ] Able to include code
- [ ] Able to new line

**Comment by imf-ali** [comment]
Hey @sidmohanty11 I would like to work on this enhancement. Please assign me.

**Comment by sidmohanty11** [comment]
@imf-ali This will be awesome! Go ahead!
